runtime: python311
entrypoint: gunicorn -b :$PORT wsgi:app
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11.4"
env_variables:
    # App configuration
instance_class: F4_1G
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network:
  session_affinity: true
inbound_services:
  - warmup